### ISSUE TITLE
Which Cradano Kupo are we using?

### ISSUE THREAD

**Issue by link78** [cardano-miners/fortuna#27]
There are 2 Kupo: the one with Mainnet-Kupo and just Mainnet.

**Comment by jabteles** [comment]
Are you referring to Mainnet-Fortuna and Mainnet?

Mainnet-Fortuna never worked for me so I used Mainnet but these are shared instances, the best is for you to create your private instance:

https://twitter.com/DemeterRun/status/1697348410754363812?s=20

**Comment by link78** [comment]
Thanks, can I use one Omigo instance for many miners?
