### ISSUE TITLE
How to create a env. file ?

### ISSUE THREAD

**Issue by dan22101979** [cardano-miners/fortuna#36]
I'm stuck at step 4 of this tutorial because I don't know how to create a .env file:

https://medium.com/p/4b595d8a4a4

How to create a env. file ?

![image](https://github.com/aiken-lang/fortuna/assets/133576171/2b639e23-a9a8-406f-a127-9d66737cfa96)

**Comment by caike** [comment]
You create a file with the exact name `.env` and then add those lines (KUPO_URL=... etc) inside that file.
